# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Business',
        ),
    ]
