# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20171116_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
