# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_auto_20171127_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
