# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 16, 3, 35, 429163, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images'),
        ),
    ]
